language: ruby

sudo: false

rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - rbx-2.2.10
  - jruby-19mode
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

gemfile:
  - Gemfile
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rack_1.5.2.gemfile
